# Generated by Django 5.2 on 2025-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('resume_file_name', models.CharField(max_length=255)),
                ('resume_skills', models.JSONField(default=list)),
                ('github_skills', models.JSONField(default=list)),
                ('verification_result', models.JSONField(default=dict)),
                ('hash_value', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
