# Generated by Django 5.2 on 2025-11-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_verifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillverification',
            name='hash_value',
            field=models.CharField(max_length=255),
        ),
    ]
